# -*- coding: utf-8 -*-
"""RC-MR3_Roof_Hourly_cropped.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123ng89-ZTnk-D9VCjjJFvfIX1ewtEHdm
"""

import io

import matplotlib.pyplot as plt
import pandas as pd


def plot_hourly_heatmap_stretched(csv_string: str) -> None:
    # Parse the CSV data
    df = pd.read_csv(io.StringIO(csv_string.strip()))

    # STRETCHED: Changed figsize width from 5 to 10
    fig, axes = plt.subplots(1, 4, figsize=(10, 8), gridspec_kw={'wspace': 0.6})

    # Extract only the data columns
    columns = df.columns[1:]

    for i, col in enumerate(columns):
        ax = axes[i]

        # Reshape data to 2D for imshow (24 rows, 1 column)
        data = df[col].values.reshape(-1, 1)

        # Plot heatmap
        im = ax.imshow(
            data,
            cmap='RdYlBu_r',
            vmin=0,
            vmax=900,
            origin='lower',
            extent=[0, 1, 0, 24],
            aspect='auto'
        )

        # Format X-axis (Month/Year labels)
        ax.set_xticks([])
        label = col.split(' (')[0].replace(' ', '\n')
        ax.set_xlabel(label, fontsize=14)

        # Format Y-axis (Time labels)
        if i == 0:
            ax.set_yticks([0, 6, 12, 18, 24])
            ax.set_yticklabels(['12 AM', '6 AM', '12 PM', '6 PM', '12 AM'], fontsize=14)
            ax.tick_params(axis='y', length=0)
        else:
            ax.set_yticks([])

        # Remove borders
        for spine in ax.spines.values():
            spine.set_visible(False)

    # REPOSITIONED COLORBAR: Adjusted for the wider figure canvas
    cbar_ax = fig.add_axes([0.92, 0.12, 0.02, 0.76])
    cbar = fig.colorbar(im, cax=cbar_ax)
    cbar.ax.set_title('kWh/m2\n', fontsize=12)
    cbar.set_ticks(range(0, 901, 90))
    cbar.ax.tick_params(labelsize=12)
    cbar.outline.set_visible(False)

    plt.show()


# Example Call with the provided data
csv_data = """Time,Mar 21 (kWh/m2),Jun 21 (kWh/m2),Sep 21 (kWh/m2),Dec 21 (kWh/m2)
12:00 AM,0.0,0.0,0.0,0.0
1:00 AM,0.0,0.0,0.0,0.0
2:00 AM,0.0,0.0,0.0,0.0
3:00 AM,0.0,0.0,0.0,0.0
4:00 AM,0.0,0.0,0.0,0.0
5:00 AM,0.0,162.3,0.0,0.0
6:00 AM,162.3,245.3,0.0,0.0
7:00 AM,245.3,407.6,243.5,0.0
8:00 AM,326.5,490.6,326.5,162.3
9:00 AM,490.6,652.9,490.6,0.0
10:00 AM,490.6,735.9,571.7,245.3
11:00 AM,571.7,817.0,652.9,326.5
12:00 PM,571.7,817.0,652.9,326.5
1:00 PM,490.6,735.9,571.7,245.3
2:00 PM,407.6,652.9,490.6,162.3
3:00 PM,245.3,571.7,407.6,0.0
4:00 PM,162.3,407.6,243.5,0.0
5:00 PM,0.0,245.3,0.0,0.0
6:00 PM,0.0,162.3,0.0,0.0
7:00 PM,0.0,0.0,0.0,0.0
8:00 PM,0.0,0.0,0.0,0.0
9:00 PM,0.0,0.0,0.0,0.0
10:00 PM,0.0,0.0,0.0,0.0
11:00 PM,0.0,0.0,0.0,0.0"""

plot_hourly_heatmap_stretched(csv_data)
