# -*- coding: utf-8 -*-
"""RC1_Wall_Hourly_cropped.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123ng89-ZTnk-D9VCjjJFvfIX1ewtEHdm
"""

import io

import matplotlib.pyplot as plt
import pandas as pd


def plot_hourly_heatmap_stretched(csv_string: str) -> None:
    # Parse the CSV data
    df = pd.read_csv(io.StringIO(csv_string.strip()))

    # STRETCHED: Changed figsize width from 5 to 10
    fig, axes = plt.subplots(1, 4, figsize=(10, 8), gridspec_kw={'wspace': 0.6})

    # Extract only the data columns
    columns = df.columns[1:]

    for i, col in enumerate(columns):
        ax = axes[i]

        # Reshape data to 2D for imshow (24 rows, 1 column)
        data = df[col].values.reshape(-1, 1)

        # Plot heatmap
        im = ax.imshow(
            data,
            cmap='RdYlBu_r',
            vmin=0,
            vmax=900,
            origin='lower',
            extent=[0, 1, 0, 24],
            aspect='auto'
        )

        # Format X-axis (Month/Year labels)
        ax.set_xticks([])
        label = col.split(' (')[0].replace(' ', '\n')
        ax.set_xlabel(label, fontsize=14)

        # Format Y-axis (Time labels)
        if i == 0:
            ax.set_yticks([0, 6, 12, 18, 24])
            ax.set_yticklabels(['12 AM', '6 AM', '12 PM', '6 PM', '12 AM'], fontsize=14)
            ax.tick_params(axis='y', length=0)
        else:
            ax.set_yticks([])

        # Remove borders
        for spine in ax.spines.values():
            spine.set_visible(False)

    # REPOSITIONED COLORBAR: Adjusted for the wider figure canvas
    cbar_ax = fig.add_axes([0.92, 0.12, 0.02, 0.76])
    cbar = fig.colorbar(im, cax=cbar_ax)
    cbar.ax.set_title('kWh/m2\n', fontsize=12)
    cbar.set_ticks(range(0, 901, 90))
    cbar.ax.tick_params(labelsize=12)
    cbar.outline.set_visible(False)

    plt.show()


# Example Call with the provided data
csv_data = """Time,Mar 21 (kWh/m2),Jun 21 (kWh/m2),Sep 21 (kWh/m2),Dec 21 (kWh/m2)
12:00 AM,0.00,0.00,0.00,0.00
1:00 AM,0.00,0.00,0.00,0.00
2:00 AM,0.00,0.00,0.00,0.00
3:00 AM,0.00,0.00,0.00,0.00
4:00 AM,0.00,0.00,0.00,0.00
5:00 AM,0.00,0.00,0.00,0.00
6:00 AM,0.00,0.00,0.00,0.00
7:00 AM,0.00,0.00,0.00,0.00
8:00 AM,180.00,180.00,180.00,180.00
9:00 AM,360.00,360.00,360.00,360.00
10:00 AM,540.00,450.00,540.00,540.00
11:00 AM,630.00,540.00,720.00,630.00
12:00 PM,720.00,630.00,900.00,720.00
1:00 PM,720.00,630.00,900.00,720.00
2:00 PM,630.00,540.00,720.00,630.00
3:00 PM,540.00,450.00,540.00,540.00
4:00 PM,360.00,360.00,360.00,360.00
5:00 PM,180.00,180.00,180.00,180.00
6:00 PM,90.00,90.00,90.00,90.00
7:00 PM,0.00,0.00,0.00,0.00
8:00 PM,0.00,0.00,0.00,0.00
9:00 PM,0.00,0.00,0.00,0.00
10:00 PM,0.00,0.00,0.00,0.00
11:00 PM,0.00,0.00,0.00,0.00"""

plot_hourly_heatmap_stretched(csv_data)