# -*- coding: utf-8 -*-
"""RC-T_Wall_Hourly_cropped.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123ng89-ZTnk-D9VCjjJFvfIX1ewtEHdm
"""

import io

import matplotlib.pyplot as plt
import pandas as pd


def plot_hourly_heatmap_stretched(csv_string: str) -> None:
    # Parse the CSV data
    df = pd.read_csv(io.StringIO(csv_string.strip()))

    # STRETCHED: Changed figsize width from 5 to 10
    fig, axes = plt.subplots(1, 4, figsize=(10, 8), gridspec_kw={'wspace': 0.6})

    # Extract only the data columns
    columns = df.columns[1:]

    for i, col in enumerate(columns):
        ax = axes[i]

        # Reshape data to 2D for imshow (24 rows, 1 column)
        data = df[col].values.reshape(-1, 1)

        # Plot heatmap
        im = ax.imshow(
            data,
            cmap='RdYlBu_r',
            vmin=0,
            vmax=900,
            origin='lower',
            extent=[0, 1, 0, 24],
            aspect='auto'
        )

        # Format X-axis (Month/Year labels)
        ax.set_xticks([])
        label = col.split(' (')[0].replace(' ', '\n')
        ax.set_xlabel(label, fontsize=14)

        # Format Y-axis (Time labels)
        if i == 0:
            ax.set_yticks([0, 6, 12, 18, 24])
            ax.set_yticklabels(['12 AM', '6 AM', '12 PM', '6 PM', '12 AM'], fontsize=14)
            ax.tick_params(axis='y', length=0)
        else:
            ax.set_yticks([])

        # Remove borders
        for spine in ax.spines.values():
            spine.set_visible(False)

    # REPOSITIONED COLORBAR: Adjusted for the wider figure canvas
    cbar_ax = fig.add_axes([0.92, 0.12, 0.02, 0.76])
    cbar = fig.colorbar(im, cax=cbar_ax)
    cbar.ax.set_title('kWh/m2\n', fontsize=12)
    cbar.set_ticks(range(0, 901, 90))
    cbar.ax.tick_params(labelsize=12)
    cbar.outline.set_visible(False)

    plt.show()


# Example Call with the provided data
csv_data = """Time,Mar 21 (kWh/m2),Jun 21 (kWh/m2),Sep 21 (kWh/m2),Dec 21 (kWh/m2)
12:00 AM,167.7,167.7,167.7,167.7
1:00 AM,167.7,167.7,167.7,167.7
2:00 AM,167.7,167.7,167.7,167.7
3:00 AM,167.7,167.7,167.7,167.7
4:00 AM,167.7,167.7,167.7,167.7
5:00 AM,241.7,241.7,167.7,167.7
6:00 AM,313.8,241.7,313.8,167.7
7:00 AM,387.8,313.8,459.9,241.7
8:00 AM,533.9,0.0,461.7,387.8
9:00 AM,461.7,533.9,680.0,459.9
10:00 AM,606.0,461.7,826.1,533.9
11:00 AM,606.0,461.7,752.1,533.9
12:00 PM,606.0,533.9,752.1,459.9
1:00 PM,313.8,313.8,533.9,241.7
2:00 PM,241.7,241.7,387.8,167.7
3:00 PM,167.7,241.7,241.7,167.7
4:00 PM,167.7,167.7,167.7,167.7
5:00 PM,167.7,167.7,167.7,167.7
6:00 PM,167.7,167.7,167.7,167.7
7:00 PM,167.7,167.7,167.7,167.7
8:00 PM,167.7,167.7,167.7,167.7
9:00 PM,95.6,95.6,95.6,95.6
10:00 PM,167.7,0.0,167.7,167.7
11:00 PM,0.0,0.0,0.0,0.0"""

plot_hourly_heatmap_stretched(csv_data)
